USE [master]
GO

/****** Object:  Endpoint [MoMirror]    Script Date: 12/26/2017 3:07:16 AM ******/
create ENDPOINT [MoMirror] 
	STATE=STARTED
	AS TCP (LISTENER_PORT = 5022, LISTENER_IP = ALL)
	FOR DATA_MIRRORING (ROLE = PARTNER, AUTHENTICATION = CERTIFICATE server2
, ENCRYPTION = REQUIRED ALGORITHM AES)
GO

GRANT CONNECT ON ENDPOINT::MoMirror TO [server2];  
go
GRANT CONNECT ON ENDPOINT::MoMirror TO [server1];
